batch_size: 20
cpi: 2
data_name: SID_Train_20
data_root: Data/
device: cuda
dim_out: 2
early_stopping: 0
epoch: 10
fc_input: 4608
input_channel: 10
label_csv: all_data.csv
load_path: Model/ewta_20m_20
model_path: Model/mdf_5m_20
num_gaus: 5
num_hypos: 20
past: 4
validation_prop: 0.2
with_T: false
zip_path: Data/SID_Train_20.zip
