---
device: multi
dim_out: 2
dynamic_env: true
fc_input: 5760
input_channel: 10
num_hypos: 20
past_len: 4
with_T: false
---
batch_size: 8
early_stopping: 0
epoch: 20
validation_prop: 0.2
---
data_name: SDD_15_test_hyang0
data_path: Data/SDD_15_test_hyang0
label_csv: all_data.csv
label_path: Data/SDD_15_test_hyang0/all_data.csv
model_path: Model/sdd_15_ewta
